version: '3.8'
services:
  duende-idsrv:
    build: ./duende-idsrv
    ports:
      - "5000:80"
  springboot-app:
    build: ./springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - duende-idsrv
