
services:
  app:
    build:
      context: ./app
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - keycloak


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
