server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          duende:
            client-id: java-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/duende"
            scope: openid, profile
        provider:
          duende:
            authorization-uri: https://localhost:5000/connect/authorize
            token-uri: https://localhost:5000/connect/token
            user-info-uri: https://localhost:5000/connect/userinfo
            user-name-attribute: name