version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - duende-idsrv

  duende-idsrv:
    image: ghcr.io/duendesoftware/samples-aspnetcore-identityserver:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
